import { Product } from "../types/products";

export const products: Product[] = [
  {
    id: 1,
    product_key: "Product 1",
    image: "/s-o-c-i-a-l-c-u-t-aXJdmnxauwY-unsplash.jpg",
    price: 1000,
    description: "This is a description of product 1",
    images: [
      "/s-o-c-i-a-l-c-u-t-aXJdmnxauwY-unsplash.jpg",
      "/valerie-elash-gsKdPcIyeGg-unsplash.webp",
      "/rendy-novantino-_jd8I6yBWM4-unsplash.webp",
      "/alireza-dolati-OVS3rqXq9gg-unsplash.webp",
    ],
    colors: ["red", "blue", "green"],
    slug: "product-1",
  },
  {
    id: 2,
    product_key: "Yellow Dress for Women - New Arrival",
    image: "/rendy-novantino-_jd8I6yBWM4-unsplash.webp",
    price: 2000,
    description:
      "Great quality, comfortable and stylish. Perfect for any occasion. New Arrival from our winter collection 2025",
    images: [
      "/rendy-novantino-_jd8I6yBWM4-unsplash.webp",
      "/alireza-dolati-OVS3rqXq9gg-unsplash.webp",
      "/rendy-novantino-_jd8I6yBWM4-unsplash.webp",
    ],
    colors: ["green", "blue", "purple"],
    slug: "yellow-dress-for-women-new-arrival",
  },
  {
    id: 3,
    product_key: "Product 3",
    image: "/valerie-elash-gsKdPcIyeGg-unsplash.webp",
    price: 3000,
    description: "This is a description of product 3",
    images: [
      "/valerie-elash-gsKdPcIyeGg-unsplash.webp",
      "/rendy-novantino-_jd8I6yBWM4-unsplash.webp",
    ],
    colors: ["green", "blue", "purple"],
    slug: "product-3",
  },
  {
    id: 4,
    product_key: "Product 4",
    image: "/alireza-dolati-OVS3rqXq9gg-unsplash.webp",
    price: 4000,
    description: "This is a description of product 4",
    images: [
      "/alireza-dolati-OVS3rqXq9gg-unsplash.webp",
      "/alireza-dolati-OVS3rqXq9gg-unsplash.webp",
    ],
    colors: ["green", "blue", "purple"],
    slug: "product-4",
  },
  {
    id: 5,
    product_key: "Product 5",
    image: "/s-o-c-i-a-l-c-u-t-aXJdmnxauwY-unsplash.jpg",
    price: 5000,
    description: "This is a description of product 5",
    images: [
      "/s-o-c-i-a-l-c-u-t-aXJdmnxauwY-unsplash.jpg",
      "/s-o-c-i-a-l-c-u-t-aXJdmnxauwY-unsplash.jpg",
    ],
    colors: ["green", "blue", "purple"],
    slug: "product-5",
  },
  {
    id: 6,
    product_key: "Product 6",
    image: "/valerie-elash-gsKdPcIyeGg-unsplash.webp",
    price: 6000,
    description: "This is a description of product 6",
    images: [
      "/valerie-elash-gsKdPcIyeGg-unsplash.webp",
      "/valerie-elash-gsKdPcIyeGg-unsplash.webp",
    ],
    colors: ["green", "blue", "purple"],
    slug: "product-6",
  },
  {
    id: 7,
    product_key: "Product 7",
    image: "/rendy-novantino-_jd8I6yBWM4-unsplash.webp",
    price: 7000,
    description: "This is a description of product 7",
    images: [
      "/rendy-novantino-_jd8I6yBWM4-unsplash.webp",
      "/rendy-novantino-_jd8I6yBWM4-unsplash.webp",
    ],
    colors: ["green", "blue", "purple"],
    slug: "product-7",
  },
  {
    id: 8,
    product_key: "Product 8",
    image: "/alireza-dolati-OVS3rqXq9gg-unsplash.webp",
    price: 8000,
    description: "This is a description of product 8",
    images: [
      "/alireza-dolati-OVS3rqXq9gg-unsplash.webp",
      "/alireza-dolati-OVS3rqXq9gg-unsplash.webp",
    ],
    colors: ["green", "blue", "purple"],
    slug: "product-8",
  },
  {
    id: 9,
    product_key: "Product 9",
    image: "/s-o-c-i-a-l-c-u-t-aXJdmnxauwY-unsplash.jpg",
    price: 9000,
    description: "This is a description of product 9",
    images: [
      "/s-o-c-i-a-l-c-u-t-aXJdmnxauwY-unsplash.jpg",
      "/s-o-c-i-a-l-c-u-t-aXJdmnxauwY-unsplash.jpg",
    ],
    colors: ["green", "blue", "purple"],
    slug: "product-9",
  },
];
